### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by olliencc** [torpyorg/torpy#1]
Downloading new consensus from longclaw authority

Connecting to guard node 46.166.182.20:443 (chungus; Tor 0.4.0.5)...
Sending: GET https://ifconfig.me
Creating new circuit #80000001 with 46.166.182.20:443 (chungus; Tor 0.4.0.5) router...
Closing guard connections...
Destroy circuit #80000001
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torpy/http/requests.py", line 58, in tor_requests_session
    yield s
  File "/usr/local/lib/python3.6/dist-packages/torpy/cli/console.py", line 47, in main
    response = s.send(request.prepare())
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/dist-packages/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/torpy/http/adapter.py", line 103, in _new_conn
    circuit = self._tor_info.get_circuit(self.host)
  File "/usr/local/lib/python3.6/dist-packages/torpy/http/adapter.py", line 45, in get_circuit
    circuit = self._guard.create_circuit_(self._hops_count)
  File "/usr/local/lib/python3.6/dist-packages/torpy/utils.py", line 69, in newfn
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torpy/client.py", line 186, in create_circuit_
    circuit.create(self)
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 271, in create
    self._circuit_nodes = self._initialize(self._router)
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 318, in _initialize
    onion_skin = circuit_node.create_onion_skin()
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 82, in create_onion_skin
    return self.key_agreement.handshake
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 69, in key_agreement
    self._key_agreement = CircuitNode._get_key_agreement(self._router, self._handshake_type)
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 75, in _get_key_agreement
    return NtorKeyAgreement(onion_router)
  File "/usr/local/lib/python3.6/dist-packages/torpy/keyagreement.py", line 166, in __init__
    self._handshake += curve25519_to_bytes(self._B)
  File "/usr/local/lib/python3.6/dist-packages/torpy/crypto_common.py", line 96, in curve25519_to_bytes
    return key.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
  File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/torpy_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/torpy/cli/console.py", line 55, in main
    logger.warning(textwrap.indent(response.text, '> ', lambda line: True))
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/torpy/http/requests.py", line 58, in tor_requests_session
    yield s
  File "/usr/local/lib/python3.6/dist-packages/torpy/http/requests.py", line 37, in __exit__
    self._guard.close()
  File "/usr/local/lib/python3.6/dist-packages/torpy/client.py", line 147, in close
    self._destroy_all_circuits()
  File "/usr/local/lib/python3.6/dist-packages/torpy/client.py", line 155, in _destroy_all_circuits
    self.destroy_circuit(circuit)
  File "/usr/local/lib/python3.6/dist-packages/torpy/client.py", line 204, in destroy_circuit
    circuit.destroy(send_destroy=send_destroy)
  File "/usr/local/lib/python3.6/dist-packages/torpy/circuit.py", line 298, in destroy
    raise Exception('#%x circuit is not yet connected')
Exception: #%x circuit is not yet connected

**Comment by olliencc** [comment]
Fixed by upgrading to 3.7

**Comment by jbrown299** [comment]
Python 3.6 must work fine. The problem happens when `cryptography<=2.4.2`. So I updated project dependencies.
