### ISSUE TITLE
cannot find path specified: AppData/Roaming/torpy/torpy

### ISSUE THREAD

**Issue by 1002666849** [torpyorg/torpy#2]
I did a pip install torpy and attempted to run one of the commands in the readme but resulted in the following error:

PS C:\Windows\system32> torpy_cli --url https://ifconfig.me --header "User-Agent" "curl/7.37.0"
Traceback (most recent call last):
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\infer\AppData\Local\Programs\Python\Python37-32\Scripts\torpy_cli.exe\__main__.py", line 9, in <module>
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\cli\console.py", line 42, in main
    with tor_requests_session(args.hops, args.headers, args.auth_data) as s:
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\http\requests.py", line 57, in tor_requests_session
    with TorRequests(hops_count, headers, auth_data) as tr:
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\http\requests.py", line 32, in __enter__
    self._tor = TorClient(auth_data=self._auth_data)
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\client.py", line 30, in __init__
    self._consensus = consensus or TorConsensus()
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\consesus.py", line 138, in __init__
    self._cache_storage = cache_storage or TorCacheDirStorage()
  File "c:\users\infer\appdata\local\programs\python\python37-32\lib\site-packages\torpy\cache_storage.py", line 35, in __init__
    os.mkdir(self._base_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\infer\\AppData\\Roaming\\torpy\\torpy'

Attempting to run other commands results in the same error.

**Comment by jbrown299** [comment]
Thanks for report. It was Windows specific bug that why I was not catch it.
More over, I added running tests on Windows through appveyor.
