### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable in /torpy/hiddenservice.py

### ISSUE THREAD

**Issue by Aniell4** [torpyorg/torpy#27]
Traceback (most recent call last):
  File "/home/aniell4/github/hidden/client123.py", line 146, in run
    with self.create_socket(dst, port) as ssock:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/aniell4/github/hidden/client123.py", line 111, in create_socket
    with self.circuit.create_stream((dst, port)) as tor_stream:
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/circuit.py", line 320, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/circuit.py", line 599, in create_stream
    tor_stream.connect(address)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/stream.py", line 267, in connect
    self._circuit.extend_to_hidden(hidden_service)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/circuit.py", line 320, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/circuit.py", line 653, in extend_to_hidden
    for responsible_dir in connector.get_responsibles_dir(hidden_service):
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/hiddenservice.py", line 144, in get_responsibles_dir
    for i, responsible_router in enumerate(self._consensus.get_responsibles(hidden_service)):
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/consesus.py", line 449, in get_responsibles
    descriptor_id = hidden_service.get_descriptor_id(replica)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/hiddenservice.py", line 134, in get_descriptor_id
    buff = self._permanent_id + self._get_secret_id(replica)
  File "/home/aniell4/.local/lib/python3.8/site-packages/torpy/hiddenservice.py", line 123, in _get_secret_id
    permanent_byte = self._permanent_id[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by jbrown299** [comment]
fixed in v1.1.6
