### ISSUE TITLE
ImportError: libssl.so.1.0.0: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by sinancetinkaya** [torpyorg/torpy#5]
Is there a way to run your script on my linux TV box?
Error I get:
```
CoreELEC:/var/media/external # torpy_socks -p 1050 --hops 3
Traceback (most recent call last):
  File "/opt/bin/torpy_socks", line 11, in <module>
    load_entry_point('torpy==1.0.10', 'console_scripts', 'torpy_socks')()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/lib/python3.7/site-packages/torpy/__init__.py", line 16, in <module>
    from torpy.client import TorClient
  File "/opt/lib/python3.7/site-packages/torpy/client.py", line 22, in <module>
    from torpy.guard import TorGuard
  File "/opt/lib/python3.7/site-packages/torpy/guard.py", line 19, in <module>
    from torpy.cells import CellRelay, CellDestroy, CellCreated2, CellRelayTruncated
  File "/opt/lib/python3.7/site-packages/torpy/cells.py", line 22, in <module>
    from torpy.crypto import hybrid_encrypt
  File "/opt/lib/python3.7/site-packages/torpy/crypto.py", line 19, in <module>
    from torpy.crypto_common import sha1, aes_update, rsa_encrypt, rsa_load_der, aes_ctr_encryptor
  File "/opt/lib/python3.7/site-packages/torpy/crypto_common.py", line 30, in <module>
    bend = default_backend()
  File "/__init__.py", line 15, in default_backend
  File "/__init__.py", line 7, in <module>
  File "/backend.py", line 71, in <module>
  File "/binding.py", line 195, in <module>
  File "/binding.py", line 142, in init_static_locks
ImportError: libssl.so.1.0.0: wrong ELF class: ELFCLASS32
```

Device details:

```
CoreELEC:~ # cat /etc/*-release
NAME="CoreELEC"
VERSION="9.0.1"
ID="coreelec"
VERSION_ID="9.0"
PRETTY_NAME="CoreELEC (official): 9.0.1"
HOME_URL="https://coreelec.org"
BUG_REPORT_URL="https://github.com/CoreELEC/CoreELEC"
BUILD_ID="df47d9506043985aa1dd1f71a79cecd9dacd275d"
COREELEC_ARCH="Amlogic.arm"
COREELEC_BUILD="official"
COREELEC_PROJECT="Amlogic"
```

**Comment by jbrown299** [comment]
Can you show?
```
uname -a 
file `which python`
python --version
```

**Comment by sinancetinkaya** [comment]
> 
> 
> Can you show?
> 
> ```
> uname -a 
> file `which python`
> python --version
> ```

```
CoreELEC:~ # uname -a
Linux CoreELEC 3.14.29 #1 SMP Tue Jul 2 16:43:47 BST 2019 aarch64 GNU/Linux
CoreELEC:~ # file `which python`
-sh: file: not found
CoreELEC:~ # python --version
Python 2.7.15
CoreELEC:~ # python3 --version
Python 3.7.1
CoreELEC:~ #

```

torpy is installed in Python 3.7.1
